{% set name = "sphinx-inline-tabs" %}
{% set version = "2023.4.21" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_inline_tabs-{{ version }}.tar.gz
  sha256: 5df2f13f602c158f3f5f6c509e008aeada199a8c76d97ba3aa2822206683bebc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=2,<4
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - sphinx >3

test:
  imports:
    - sphinx_inline_tabs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pradyunsg/sphinx-inline-tabs
  summary: Add inline tabbed content to your Sphinx documentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
